language: java

jdk:
  - openjdk11

install: true

git:
  depth: false

addons:
  sonarcloud:
    organization: simonharmonicminor

script:
  - "./gradlew clean build jacocoTestReport sonarqube"

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.gradle"
    - ".gradle"